### ISSUE TITLE
[Feedback] and Question

### ISSUE THREAD

**Issue by zero-arc** [doudoudzj/myownfreehost-template#1]
Thank you very much for making this!!
It's very friendly and clean UI! 😀
Thank you! 
And also I have one question,
What am I not allowed to edit?

**Comment by zero-arc** [comment]
And also how to edit the logo or the title like  I want to change UIISC to my branding,
Please do answer!

**Comment by jksdou** [comment]
@arcenas090 you can edit the title in file core.php
and you can use it for free

**Comment by 4yx** [comment]
Thanks for replying to arcenas, you also solved my question. Nice theme :smile:
