### ISSUE TITLE
what to enter in Callback Token?? 

### ISSUE THREAD

**Issue by karandev79** [doudoudzj/myownfreehost-template#13]
what to enter in Callback Token?? 
atleast create a docs if you want users to use your client system.

**Comment by karandev79** [comment]
totally died support

**Comment by ash3T** [comment]
> what to enter in Callback Token?? atleast create a docs if you want users to use your client system.

Are you able to install it? Can you share what do you did? Thanks.

**Comment by kairavsharma-eot** [comment]
na its not working correctly.

**Comment by whatbeato** [comment]
> > what to enter in Callback Token?? atleast create a docs if you want users to use your client system.
> 
> Are you able to install it? Can you share what do you did? Thanks.

it has reached a point where no one uses this. this ui is amazing and i really want to use it...
