### ISSUE TITLE
bug when i upload demo.sql

### ISSUE THREAD

**Issue by mahdimehri** [doudoudzj/myownfreehost-template#4]
hi  @uiisc
when I upload demo.sql show me some warning (PHPMyAdmin)
and in clientarea.php show me this error 
Fatal error: Uncaught Exception: MySQL Error: SQLSTATE[HY000] [2002] No such file or directory in /home/vol11_2/akiraserver.ir/www/htdocs/library/pdo.class.php:497 Stack trace: #0 /home/vol11_2/akiraserver.ir/www/htdocs/library/pdo.class.php(24): DBPDO->outputError('SQLSTATE[HY000]...') #1 /home/vol11_2/akiraserver.ir/www/htdocs/library/pdo.class.php(43): 
DBPDO->__construct(Array) #2 /home/vol11_2/akiraserver.ir/www/htdocs/clientarea.php(15): DBPDO::getInstance(Array) #3 {main} thrown in /home/vol11_2/akiraserver.ir/www/htdocs/library/pdo.class.php on line 497

what should i do ?
plasse help me

**Comment by jksdou** [comment]
@mahdimehri We have a new version under development and hope to solve this problem

**Comment by jksdou** [comment]
> 

Maybe your database can't be connected. Sorry for replying so late
